---
title: "p8105_hw3_yl5829"
output: github_document
date: "2024-10-12"
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)

library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

##Problem 1

```{r}
data("ny_noaa")
```


##Problem 2

```{r}
demo <- read.csv("data/nhanes_covar.csv")
accel <- read.csv("data/nhanes_accel.csv")

#tidy demographic data by renaming columns
demo <- demo %>%
  rename(
    seqn = X,
    sex = X1...male,
    age = X.1,
    BMI = X.2,
    education = X1...Less.than.high.school 
  ) %>%
  filter(age >= 21) %>%
  drop_na(sex, age, BMI, education) %>%
  mutate(
    sex = factor(sex, levels = c(1, 2), labels = c("Male", "Female")),
    education = factor(education, levels = c(2, 3), labels = c("High School", "More than High School"))
  )

accel <- accel %>% rename(seqn = SEQN)

# Merge two data
merged_data <- merge(demo, accel, by = "seqn")

print(merged_data)
```

```{r}
print(demo)
print(accel)
```

